server:
  port: 8088
spring:
  profiles:
    active: local
  cloud:
    stream:
      bindings:
        output:
          destination: order-fulfillment
          content-type: application/json
        input:
          destination: order-fulfillment
          content-type: application/json
      default-binder: rabbit