server:
  port: 8090
spring:
  profiles:
    active: local
  cloud:
    stream:
      bindings:
        input:
          destination: order-fulfillment
          content-type: application/json
      default-binder: rabbit