server:
  port: 8080

camel:
  component:
    servlet:
      mapping:
        context-path: /camel/*

management:
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia

hawtio:
  authenticationEnabled: false